name: Build

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22

            - name: Build
              run: |
                  CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_win32_x64.exe
                  sudo rm -rf /home/runner/.cache/go-build
                  sudo rm -rf /home/runner/go

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest2"
                  title: Development Build2
                  prerelease: true
                  files: |
                      pty_win32_x64.exe
