name: Build

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22

            - name: Build
              run: |
                  CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_windows_amd64.exe
                  CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_amd64
                  CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_arm64
                  CGO_ENABLED=0 GOOS=linux GOARCH=arm go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_arm
                  CGO_ENABLED=0 GOOS=linux GOARCH=386 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_386
                  CGO_ENABLED=0 GOOS=linux GOARCH=loong64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_loong64
                  CGO_ENABLED=0 GOOS=linux GOARCH=mips go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_mips
                  CGO_ENABLED=0 GOOS=linux GOARCH=mips64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_mips64
                  CGO_ENABLED=0 GOOS=linux GOARCH=mips64le go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_mips64le
                  CGO_ENABLED=0 GOOS=linux GOARCH=mipsle go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_mipsle
                  CGO_ENABLED=0 GOOS=linux GOARCH=ppc64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_ppc64
                  CGO_ENABLED=0 GOOS=linux GOARCH=ppc64le go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_ppc64le
                  CGO_ENABLED=0 GOOS=linux GOARCH=riscv64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_riscv64
                  CGO_ENABLED=0 GOOS=linux GOARCH=s390x go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_linux_s390x
                  CGO_ENABLED=0 GOOS=netbsd GOARCH=386 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_netbsd_386
                  CGO_ENABLED=0 GOOS=netbsd GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_netbsd_amd64
                  CGO_ENABLED=0 GOOS=netbsd GOARCH=arm go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_netbsd_arm
                  CGO_ENABLED=0 GOOS=netbsd GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_netbsd_arm64
                  CGO_ENABLED=0 GOOS=openbsd GOARCH=386 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_openbsd_386
                  CGO_ENABLED=0 GOOS=openbsd GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_openbsd_amd64
                  CGO_ENABLED=0 GOOS=openbsd GOARCH=arm go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_openbsd_arm
                  CGO_ENABLED=0 GOOS=openbsd GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_openbsd_arm64
                  CGO_ENABLED=0 GOOS=freebsd GOARCH=386 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_freebsd_386
                  CGO_ENABLED=0 GOOS=freebsd GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_freebsd_amd64
                  CGO_ENABLED=0 GOOS=freebsd GOARCH=arm go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_freebsd_arm
                  CGO_ENABLED=0 GOOS=freebsd GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_freebsd_arm64
                  CGO_ENABLED=0 GOOS=freebsd GOARCH=riscv64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_freebsd_riscv64
                  CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_darwin_amd64
                  CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -v -ldflags="-compressdwarf=false" -gcflags '-E -I -L -N -complete -v' -o pty_darwin_arm64
                  sudo rm -rf /home/runner/.cache/go-build
                  sudo rm -rf /home/runner/go

            - uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  title: Development Build
                  prerelease: true
                  files: |
                      pty_windows_amd64.exe
                      pty_linux_amd64
                      pty_linux_arm64
                      pty_linux_arm
                      pty_linux_386
                      pty_linux_loong64
                      pty_linux_mips
                      pty_linux_mips64
                      pty_linux_mips64le
                      pty_linux_mipsle
                      pty_linux_ppc64
                      pty_linux_ppc64le
                      pty_linux_riscv64
                      pty_linux_s390x
                      pty_netbsd_386
                      pty_netbsd_amd64
                      pty_netbsd_arm
                      pty_netbsd_arm64
                      pty_openbsd_386
                      pty_openbsd_amd64
                      pty_openbsd_arm
                      pty_openbsd_arm64
                      pty_freebsd_386
                      pty_freebsd_amd64
                      pty_freebsd_arm
                      pty_freebsd_arm64
                      pty_freebsd_riscv64
                      pty_darwin_amd64
                      pty_darwin_arm64
